language: php

php:
  - 7.1

before_script:
  - cp .env.travis .env
  - composer install --no-interaction
  - composer dump-autoload

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml
after_success:
  - bash <(curl -s https://codecov.io/bash)
